### ISSUE TITLE
test_jks crashes in release mode.

### ISSUE THREAD

**Issue by madf** [dstucrypt/dstu-engine#12]
Backtrace:
```
Starting program: /home/faust/Projects/dstu-engine/build/tests/test_jks
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7d67945 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
(gdb) bt
#0  0x00007ffff7d67945 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#1  0x00007ffff7d65ca8 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#2  0x00007ffff7d65dc5 in ASN1_item_free () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
#3  0x00007ffff7fc14ed in JKSEntryFree () from /home/faust/Projects/dstu-engine/build/keylib/libkeylib.so
#4  0x00007ffff7fc159d in JKSFree () from /home/faust/Projects/dstu-engine/build/keylib/libkeylib.so
#5  0x00005555555569d4 in main ()
```

**Comment by madf** [comment]
Fixed in 1.2.2
